db/migrations/000095-01-alter-table-electricity_types-add-position.js
db/migrations/000095-02-alter-table-field_types-add-position.js
db/migrations/000095-03-alter-table-owner_types-add-position.js
server/models/electricityTypeModel.js
server/models/fieldTypeModel.js
server/models/ownerTypeModel.js

https://trello.com/c/FV52w3Ja/564-formulaire-ordre-des-r%C3%A9ponses-oui-non-inconnu
Scripts de migration pour ajouter le champ position + modifications des requetes findAll pour sort par position
Related PR : https://github.com/MTES-MCT/action-bidonvilles/pull/4

Création site - ordre des réponses "oui, non, inconnu"

---

.gitignore
db/migrations/000094-01-alter-table-shantytowns-add-closed_with_solutions.js
db/migrations/000094-02-alter-table-shantytowns-add-constraint-on-closed_with_solutions.js
db/models/shantytowns.js
server/controllers/townController.js
server/controllers/townController/helpers/cleanParams.js
server/models/shantytownModel.js
test/suites/server/controllers/townController/close.spec.js

https://trello.com/c/5faOhDW1/551-mesurer-le-nombre-de-site-r%C3%A9sorb%C3%A9s
J'ai repris ce qu'on a fait en pair programming + rajouté des tests unitaires couvrant ce nouveau champ
Related PR : https://github.com/MTES-MCT/action-bidonvilles/pull/3

Changements backend pour l'ajout du champ "Est-ce que le site a été résorbé définitivement?"

---

db/migrations/000098-01-alter-table-shantytowns-add-name.js
db/models/shantytowns.js
server/controllers/townController.js
server/controllers/townController/edit.js
server/controllers/townController/helpers/cleanParams.js
server/controllers/townController/helpers/validateInput.js
server/loaders/routesLoader.js
server/mails/comment_deletion.js
server/models/shantytownModel.js

https://trello.com/c/RkEF16uf/542-formulaire-ajout-du-champ-appellation-du-site
Related PR: https://github.com/MTES-MCT/action-bidonvilles/pull/9

Ajout du champ "Appellation du site"

---

server/models/planModel.js

Ticket #588 : https://trello.com/c/XLlvt0v9/588-d%C3%A9claration-du-dispositif-changer-le-wording-de-la-cat%C3%A9gorie-dans-plusieurs-lieux-par-dans-plusieurs-lieux-h%C3%A9bergement-permanenc
Voir également la PR côté front : https://github.com/MTES-MCT/action-bidonvilles/pull/23

Wording sur le formulaire des dispositifs

---

server/middlewares/validators/common/writeTown.js

Ticket : https://trello.com/c/oiNJlOqC/595-retirer-la-restriction-sur-lorigine-des-personnes-intra-extra-ue-pour-les-sites-de-moins-de-10-personnes

(595) Lever la restriction sur les origines

---

server/middlewares/validators/common/writeTown.js

Ticket : https://trello.com/c/6I46BxgM/261-formulaire-ne-pas-rendre-obligatoire-le-d%C3%A9p%C3%B4t-de-plainte-pour-pouvoir-d%C3%A9clarer-une-proc%C3%A9dure-judiciaire

(261) Le dépôt de plainte est désormais facultatif

---

package.json
server/controllers/townController.js
server/utils/slack.js
yarn.lock

https://trello.com/c/bZvCzSzV/660-alerte-slack-%C3%A0-la-cr%C3%A9ation-ou-fermeture-dun-site
```
...
slack: {
close_shantytown: 'https://hooks.slack.com/services/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',
new_shantytown: 'https://hooks.slack.com/services/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',
}
...
```
Ouverture de site (#ouverture-sites):
Fermeture de site (#fermeture-sites):

(660) Alerte slack à la création ou fermeture d'un site

---

server/middlewares/validators/common/writeTown.js

Si une permission d'écriture (create / edit) sur un site est set sur `local`, alors le niveau géographique le plus bas à prendre en compte doit être `departement` (avant on prenait strictement le niveau géographique de l'utilisateur, donc potentiellement `epci` ou `city`).
Cela permet de corriger un bug d'une utilisatrice de niveau communal qui n'arrive pas à modifier et déclarer des sites :
https://trello.com/c/45K54GbY/667

(667) Les droits minimums sur les sites se font au niveau départemental

---

db/seeders/000002-soliguide.js

Ce PR met à jour les données du soliguide à partir d'un nouveau fichier CSV
```
docker-compose exec api bash
node_modules/.bin/sequelize db:seed --seed 000002-soliguide
```

Update soliguide data

---

server/controllers/userController.js
server/loaders/agendaJobsLoader.js
server/mails/demo_invitation.js

https://trello.com/c/0yL2nRMi/692-email-automatique-pour-inviter-un-nouvel-utilisateur-a-une-d%C3%A9mo-%C3%A0-j7

Email automatique pour inviter un nouvel utilisateur a une démo à j+7

---

server/controllers/userController.js
server/utils/slack.js

https://trello.com/c/Xj4PMi1H/671-cr%C3%A9er-un-channel-slack-nouvel-utilisateur-sur-la-plateforme-avec-nom-pr%C3%A9nom-structure-fonction
L'alerte est trigger au moment de l'activation du compte (lorsqu'on saisit le mdp après avoir reçu le lien d'invitation)
Il faudra rajouter l'url du webhook dans server/config.js. Elle est sur le channel dev par soucis de sécurité (repo publique)

Création channel slack alerte utilisateur

---

server/models/geoModel.js

Ajoute le champ departement lors de la recherche de ville/epci
Lié à https://github.com/MTES-MCT/action-bidonvilles/pull/30 et à l'ajout de l'image du département/région

Add departement to /location/search API

---

db/migrations/000102-01-alter-table-indicateurs_education-add-column-en_mediation.js
server/controllers/planController.js
server/models/planModel.js

À mep avec la PR côté front : https://github.com/MTES-MCT/action-bidonvilles/pull/58

(687) Ajout d'un indicateur "Mineurs bénéficiant d'une médiation"

---

server/models/shantytownModel.js

Ajout de champs dans la sérialisation des sites qui permettent, côté front, de calculer le tableau d'évolution de la démographie.
- [701](https://trello.com/c/tEdCs5gZ/701-tableau-de-l%C3%A9volution-de-la-d%C3%A9mographie)
- https://github.com/MTES-MCT/action-bidonvilles/pull/54

(701) Tableau de l'évolution de la démographie

---

server/controllers/userController.js

https://trello.com/c/ndmKrE5g/810-corriger-le-timing-denvoi-de-la-notification-de-nouveaux-utilisateurs-sur-slack

(810) Corriger le timing d'envoi de la notification de nouveaux utilisateurs sur slack

---

db/migrations/000104-01-alter-table-shantytown-remove-priority.js
db/models/shantytowns.js
server/controllers/townController.js
server/controllers/townController/edit.js
server/middlewares/validators/common/writeTown.js
server/models/shantytownModel.js
test/fixtures/server/models/shantytownModel.fixtures.js
test/suites/server/controllers/townController/edit.spec.js
test/suites/server/middldewares/validators/createTown.spec.js
test/suites/server/models/shantytownModel.spec.js

Related PR : https://github.com/MTES-MCT/action-bidonvilles/pull/67

(746) Supprimer la "priorité" de la pop-up et de l'export liste de sites

---

package.json
server/app.js
server/config.js.sample
server/controllers/configController.js
server/controllers/directoryController.js
server/controllers/geoController.js
server/controllers/organizationController.js
server/controllers/planController.js
server/controllers/poiController.js
server/controllers/statsController.js
server/controllers/townController.js
server/controllers/townController/addActor.js
server/controllers/townController/createHighCovidComment.js
server/controllers/townController/edit.js
server/controllers/townController/getRelations.js
server/controllers/townController/inviteNewActor.js
server/controllers/townController/removeActor.js
server/controllers/townController/removeActorTheme.js
server/controllers/townController/updateActor.js
server/controllers/userActivityController.js
server/controllers/userController.js
server/index.js
server/loaders/expressLoader.js
server/loaders/routesLoader.js
server/middlewares/authMiddleware.js
test/suites/server/controllers/townController/createCovidComment.spec.js
yarn.lock

PR coté front: https://github.com/MTES-MCT/action-bidonvilles/pull/87

Ajout de Sentry pour le tracking d'erreurs

---

server/controllers/statsController.js
server/loaders/routesLoader.js
server/models/statsModel.js
server/utils/date.js

PR liée: https://github.com/MTES-MCT/action-bidonvilles/pull/108

Statistiques privés

---

server/controllers/inviteController.js
server/utils/slack.js

- branche `if` sortie d'une boucle `for` pour optimiser
- ne pas répondre une 500 en cas d'échec à envoyer une notification Slack
- correction du nom du hook Slack pour l'invitation d'un utilisateur
- ajout de l'email de la personne invitée dans la notification Slack
- linting

(981) PR feedback

---

server/controllers/inviteController.js
server/utils/slack.js

Création d'une alerte Slack pour les  invitations générées après une demande d'accès

#patch (981) - Création d'une alerte Slack pour les invitations

---

db/migrations/000107-alter-table-permissions-stats-read-local-admin.js

#patch (916) Rendre les statistiques privées accessible aux admin locaux

---

server/models/planShantytownModel.js
server/models/shantytownModel.js

https://trello.com/c/IljnECdA/931-lien-site-dispositif-avoir-sur-la-fiche-dun-site-les-dispositifs-mobilis%C3%A9s
PR Front : https://github.com/MTES-MCT/action-bidonvilles/pull/125

#minor (931) Lien site – dispositif : avoir sur la fiche d'un site les dispositifs mobilisés
